### ISSUE TITLE
Use Cloudflare D1 for database.

### ISSUE THREAD

**Issue by SunsetMkt** [CorentinTh/enclosed#245]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Provide an option to replace Cloudflare KV to D1.

Though there's no `unstorage` D1 driver currently, it's possible to implement manually.

Inspiration: https://github.com/SunsetMkt/pastebin-worker-d1/blob/d1-publish/src/db.js

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi @SunsetMkt 
I'm not sure of the benefits of using D1 over Cloudflare KV, since the latter is a key-value store with a generous free tier with TTL support. Could you provide more information on why you would need to replace Cloudflare KV with D1?

Plus in term of performance, Cloudflare KV should be better than D1

**Comment by SunsetMkt** [comment]
D1 has more free writes per day (100000) than KV (1000), as well as the reads.

**Comment by CorentinTh** [comment]
I'm closing as not planned for the moment
