### ISSUE TITLE
Option to keep note forever

### ISSUE THREAD

**Issue by ilyakonovalenko** [CorentinTh/enclosed#321]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

Currently there is no way to keep note forever. 1 month may not be enough in some cases.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by CorentinTh** [comment]
Hi!
Thank you for your feedback. Adding a "never expire" option is indeed a good idea.
Before implementing it, I have some concerns:

1. Adding another entry in the expiration delay picker may cause some overflow.
   - Option 1: Add a "never" option in the selector on the right. ![image](https://github.com/user-attachments/assets/0697e547-9613-4607-ac34-42140b804d1f)
   - Option 2: Add a "never expire" checkbox like below the picker.
   - Option 3: Use a more traditional select with dropdown, not really fan, it adds more clicks.

2. I may disable this feature for the public instance for multiple reasons:
   - The instance is free and since it's fully open-source, I don't want to pay for a lot of storage.
   - Their is a risk of abuse, someone could use the instance to store illegal content since it does not require any authentication.

Enclosed was designed to share ephemeral content, so I didn't think about adding such persistent feature. But I understand that it could be useful in some cases.

**Comment by Zoobdude** [comment]
+1 for the 'never' selector using a separate toggle.

Making it possible to disable this via a ENV var would be ideal.

**Comment by ilyakonovalenko** [comment]
Option 1 would be good, but some CSS adjustments needed (maybe lower font size or reduced padding).

**Comment by joshwithers** [comment]
I'd love to have a config page to disable this :)

**Comment by CorentinTh** [comment]
I added a toggle to allow the creation of notes that never expires, it's available for version >= [1.11.0](https://github.com/CorentinTh/enclosed/releases/tag/v1.11.0)

- Set `PUBLIC_IS_SETTING_NO_EXPIRATION_ALLOWED` to allow users to create notes that never expires, it is disabled by default
- It's disabled on the [public instance](https://enclosed.cc/)
- Additionally you can use `PUBLIC_DEFAULT_NOTE_NO_EXPIRATION` to configure weither the note should never expires by default


![image](https://github.com/user-attachments/assets/65be1a3f-04b0-4195-8c0b-a5878b55c21d)
