### ISSUE TITLE
Add 'The note never expires' to translations

### ISSUE THREAD

**Issue by SamKr** [CorentinTh/enclosed#344]
### Describe the bug

It looks like `The note never expires` hasn't been added to the language files yet:

![image](https://github.com/user-attachments/assets/fb7c8b22-1e73-4e3a-a628-5644d4abbfce)

I can't find it in `en.json` either.

### What happened?

New variable added to the interface (nice function though).

### System information

Latest version.

### Where did you encounter the bug?

Public app (enclosed.cc)

**Comment by CorentinTh** [comment]
Hi @SamKr 

Thanks for pointing that out!
The text `The note never expires` is already available under the key `create.settings.no-expiration` but currently only translated in `en` and `fr`.

Since I only speak English and French, I can't provide translations for every language in the app when adding new features. For this reason, the JSON files for other locales may have missing keys, especially as new features are added. However, the app is designed to fall back to English if a key is missing in the selected locale, which ensures functionality remains intact.

Please note that opening issues for missing translation keys isn't necessary. If you're interested, you can refer to the documentation page [here](https://docs.enclosed.cc/resources/i18n) to check the supported languages and their translation levels, including missing key counts or make a PR to add the missing keys in some locales files 

Let me know if you have any further questions or suggestions!

**Comment by SamKr** [comment]
No problem at all, thanks for pointing it out. I created a PR with the new variable, and some minor tweaks. 

Thanks for sharing this great product ❤️
