### ISSUE TITLE
Implementing API for upload of text/file through terminals

### ISSUE THREAD

**Issue by driftywinds** [CorentinTh/enclosed#352]
### What type of request is this?

New feature idea

### Clear and concise description of the feature you are proposing

I checked the docs and there doesn't seemed to be an API that lets people upload text or files straight from the terminal, meaning that people would HAVE to use the UI to do their bidding. Implementing a cURL compatible API would allow for not only terminals to interact with instances without UI but also give potential for apps on the different platforms. 

### Additional context

This project reminded me of transfer.sh, except its even more secure, but it only lacked this aspect in my opinion so I thought I should maybe try suggesting it as a feature. Please correct me if I'm wrong and this already exists.

### Validations

- [X] Check the feature is not already implemented in the project.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Check that the feature is technically feasible and aligns with the project's goals.

**Comment by Zoobdude** [comment]
Enclosed uses end to end encryption which means that the payload is encrypted on the device before being sent over the internet and only decrypted on the recipients device. Unfortunately, although it increases security, this means it's not possible to just expose an API endpoint, which is why the [CLI client](https://docs.enclosed.cc/integrations/cli) and [NPM package](https://docs.enclosed.cc/integrations/npm-package) exist to provide the tools needed to prepare and encrypt the file before sending.

Although you might ask what difference does it make encrypting it on the device before sending if HTTPS is secure already? This is because the server would still store your note in an unencrypted state. This is the difference between securing data in transit and data at rest.

Hope this explains why this wouldn't be possible, but thank you for the suggestion!

**Comment by driftywinds** [comment]
Thank you for explaining, makes sense!
