### ISSUE TITLE
Is there a limit to the attached file size?

### ISSUE THREAD

**Issue by truthsword** [CorentinTh/enclosed#365]
### Describe the bug

I'm trying to attach an 12 GB file to a note. Progress begins, and then after a minute it errors out. I don't see any meaningful log information. Is there an environmental variable (this is a docker container) that caps attachment size? Thanks!

### What happened?

Error during file upload

### System information

Running latest docker container image

### Where did you encounter the bug?

A self hosted instance

**Comment by CorentinTh** [comment]
Hello @truthsword,

Yes, there is an env variable for configuring the maximum encrypted payload size:  `NOTES_MAX_ENCRYPTED_PAYLOAD_LENGTH`
You can find it in the configuration documentation here: https://docs.enclosed.cc/self-hosting/configuration

This limit applies to the entire "payload" (encrypted files + note text content) because the app stores a single bundled and encrypted payload containing all the data (content + attachments). This is to ensure that the server cannot determine whether a note contains attachments or not

**Comment by truthsword** [comment]
Thanks!
